AMD device tree video, pcc and jtag updates
AMDESE/linux-aspeed pull request #16
Opened 2024-09-09 08:06 UTC by ojayanth

This PR includes AMD platforms  congo, morocco, marley device updates related to video, jtag and PPC nodes.

2024-09-14 20:49 UTC, mahkurap requested changes

2024-09-14 20:49 UTC, mahkurap commented on arch/arm64/boot/dts/aspeed/aspeed-bmc-amd-marley.dts
> -		pcc_memory: pccbuffer {
why is pcc_memory deleted?

2024-09-14 20:49 UTC, mahkurap commented on arch/arm64/boot/dts/aspeed/aspeed-bmc-amd-marley.dts
> +&jtag0 {
How does Tag2 with Yaapd work without this driver change?

2024-09-14 20:51 UTC, mahkurap requested changes

2024-09-14 20:51 UTC, mahkurap commented on arch/arm64/boot/dts/aspeed/aspeed-bmc-amd-congo.dts
> -		pcc_memory: pccbuffer {
why pcc_memory node deleted?

2024-09-14 20:51 UTC, mahkurap commented on arch/arm64/boot/dts/aspeed/aspeed-bmc-amd-congo.dts
> +&jtag0 {
how does tag 2 work with yaapd without enabling the device tree?

2024-09-14 20:51 UTC, mahkurap commented on arch/arm64/boot/dts/aspeed/aspeed-bmc-amd-congo.dts
> +&jtag0 {
Should we have this as a separate commit?

2024-09-14 20:53 UTC, mahkurap reviewed
Same comments as in Marley/Congo device trees

2024-10-09 10:02 UTC, ojayanth commented
Already added same support with different PR's

2024-10-09 10:02 UTC, closed without merging