AMD PRB Kenya DTS changes for v2.16.0.02C
AMDESE/linux-aspeed pull request #25
Opened 2024-10-05 20:32 UTC by modolaty

ARM64: dts: aspeed: Kenya
Copied from VRB Congo platform DTS
Add ltpi0, and i2c0 and i2c1 from ltpi
Add jtag1 for YAAP
Add uart9 for SOL
Add USB and vhub for KVM
tested and verified in Kenya platform

2024-10-07 06:50 UTC, ojayanth requested changes
Add jtag1 for YAAP  --> it will be good for adding reason for why jag0 replaced by jtag1. fro future refernce

2024-10-07 06:50 UTC, ojayanth commented on arch/arm64/boot/dts/aspeed/aspeed-bmc-amd-kenya.dts
> +		video_engine_memory0: video0 {
SDK recommends this format

video_engine_memory0: video0 { size = <0x0 0x04000000>; alignment = <0x0 0x00010000>; compatible = "shared-dma-pool"; reusable; };

2024-10-09 15:34 UTC, supven01 approved these changes

2024-10-09 15:34 UTC, supven01 commented on arch/arm64/boot/dts/aspeed/aspeed-bmc-amd-kenya.dts
> +			size = <0x0 0x04000000>;
nit: Add a comment that 64 MB buffer is being allocated.

2024-10-09 15:49 UTC, supven01 approved these changes

2024-10-09 17:07 UTC, ojayanth approved these changes

2024-10-09 17:08 UTC, merged