arm: dts: aspeed-g7: update i2c clock speed to 400khz
AMDESE/linux-aspeed pull request #39
Opened 2024-10-25 00:50 UTC by aasboddu

Modified i2c clock speed to 400khz for i2c-7,8,9,10.

Tested:- Verified on Congo and Morocco Platforms.

2024-10-25 01:50 UTC, mahkurap requested changes
instead of changing the dtsi file, overwrite this property in the corresponding device tree file.

2024-10-25 16:27 UTC, aasboddu commented
> instead of changing the dtsi file, overwrite this property in the corresponding device tree file.

Moved changes to dts file. Created individual commits for each platform.

2024-10-25 18:00 UTC, mahkurap approved these changes

2024-10-25 21:48 UTC, modolaty approved these changes

2024-10-28 19:25 UTC, supven01 approved these changes

2024-10-28 19:39 UTC, supven01 approved these changes

2024-10-28 19:39 UTC, merged